apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: iot
  name: iot-app
spec:
  project: iot-app-project
  source: 
    repoURL: http://gitlab.gitlab.svc/root/guribeir-argocd.git
    targetRevision: HEAD
    path: app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
