# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine319"

  config.vm.define "guribeirS" do |master|
    master.vm.hostname = "guribeirS"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.provider "virtualbox" do |v|
      v.gui = false
      v.name = "guribeirS"
      v.memory = 1024
      v.cpus = 1
    end
	master.vm.provision "file", source: "./config/", destination: "/home/vagrant/"
    master.vm.provision "shell", path: "./setup-k3s.sh"
  end
end
