# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  config.vm.box = "generic/alpine319"

  config.vm.define "guribeirS" do |master|
    master.vm.hostname = "guribeirS"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.provider "virtualbox" do |v|
      v.gui = false
      v.name = "guribeirS"
      v.memory = 1024
      v.cpus = 1
    end
    master.vm.provision "shell", path: "./setup-k3s.sh"
  end

  config.vm.define "guribeirSW" do |agent|
    agent.vm.hostname = "guribeirSW"
    agent.vm.network "private_network", ip: "192.168.56.111"
    agent.vm.provider "virtualbox" do |v|
      v.gui = false
      v.name = "guribeirSW"
      v.memory = 1024
      v.cpus = 1
    end
    agent.vm.provision "shell", path: "setup-k3s.sh"
  end
end
