dependencies:
- name: redis
  version: 0.7.0
  repository: "https://charts.bitnami.com/bitnami"
- name: postgresql
  version: 0.6.0
  repository: "https://charts.bitnami.com/bitnami"
- name: minio
  version: 1.3.3
  repository: "https://charts.bitnami.com/bitnami"
- name: runner
  version: 0.4.1
  repository: "https://charts.bitnami.com/bitnami"
  condition: runner.enabled
- name: registry
  version: 0.2.0
  repository: "https://charts.bitnami.com/bitnami"
  condition: registry.enabled
