apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: iot
  name: iot-app
spec:
  project: iot-app-project
  source:
    repoURL: https://github.com/guiribei/guribeir-argocd.git
    targetRevision: main
    path: app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
