apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          10.43.224.250 gitlab.gitlab.localhost
      fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          10.43.224.250 gitlab.localhost
      fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        import /etc/coredns/custom/*.override
    }
    import /etc/coredns/custom/*.server
  NodeHosts: |
    192.168.65.254 host.k3d.internal
    172.22.0.2 k3d-bonus-cluster-tools
    172.22.0.3 k3d-bonus-cluster-server-0
    172.22.0.4 k3d-bonus-cluster-serverlb
kind: ConfigMap
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yQT4vUQBDFv0pT56SddCZ/NuBB9iKIHj3tpZKubNpkqoaumpFl2O8uYRQEWfX2mtf14713Azynr5Q1CcMA1woKiGgIww0eJdOcNoIB/NDU7vbEzjlHOUvWu14IN1vuOhPGl7tcLyNlJiN103ZRo+w3gQK+SKSPoqYwQPUQfNX2vm18aI5uETW/1tEnNsqM2xNXXfAh+IMPbq1jOQpftPzJK03gtYA1cYQBHoXn9PwZz1DAiQx/NUBmMbQkrPtTxm80mZL5nMRPaLaRT/Iu7Qwo3vTlO1Mun68rDLDW+ptzrQr3KXF8/yFG4X8iGE/7mpNkiqz/9V3POO03+6SlvqjRaS++4UjbX0stqAsMME4U+jo89H1VdccaD3Xf4thUhznMbUdzdwzHw9R0O/SPeG8GeP0RAAD//77dMPs4AgAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: coredns
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2024-04-19T00:25:16Z"
  labels:
    objectset.rio.cattle.io/hash: bce283298811743a0386ab510f2f67ef74240c57
  name: coredns
  namespace: kube-system
  resourceVersion: "695"
  uid: 7f752543-c3cf-4600-8a50-93cbc2d6904c
