apiVersion: v1
kind: Service
metadata:
  name: app-one-svc
  namespace: default
  labels:
    app: app-one-svc
spec:
  selector:
    app: app-one-pod
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort